spring:
  application:
    name: cdc-sync-service
  datasource:
    url: jdbc:postgresql://localhost:5432/cdc_db
    username: postgres
    password: root
    hibernate:
      ddl-auto: update
    show-sql: true